### ISSUE TITLE
iOS native app cannot add users to private group chat

### ISSUE THREAD

**Issue by matthewbassett** [RocketChat/Rocket.Chat.iOS#2503] opened 2019-01-19 12:05 UTC
- Your Rocket.Chat app version: 3.2.0 (223)
- Your Rocket.Chat server version: 0.73.2
- Device (or Simulator) you're running with: iOS 12.0.1

When you add a new private "channel" (Private Group in the web app) from an iOS device you are not given the option to add members. Even after the channel is created if you go to the members area of the private group you are not given an invite users button. Same user same permission works on android and in the web version. Am I missing something or is that functionality not in the app yet?

**Comment by oceanho** [comment] 2019-02-02 04:17
you need a `Add User to Any Joined Channel
[add-user-to-joined-room]` permision

**Comment by oceanho** [comment] 2019-02-02 11:50
We have also encountered the same problem.

**Comment by rafaelks** [comment] 2019-02-04 12:10
@matthewbassett @oceanho Can you confirm if your users have these permissions?

- `add-user-to-joined-room`
- `add-user-to-any-p-room`

**Comment by matthewbassett** [comment] 2019-02-05 07:20
@rafaelks Just checked and standard users do not have those permissions, I added them and will test with users to see if that fixes the issue. However starting a new DM between two users works on all other RC platforms. Is there something different about the way DM's are created in the iOS app?

Thanks!

**Comment by rafaelks** [comment] 2019-02-05 09:52
@matthewbassett Starting DMs doesn't require any permission, that's the difference.

**Comment by oceanho** [comment] 2019-02-14 03:09
@rafaelks, thanks for your help.
I am sign in as administrator(has full permissions), Add button is visible, but no users are searched

**Comment by rafaelks** [comment] 2019-02-14 13:50
@oceanho The list doesn't display any user?

**Comment by oceanho** [comment] 2019-02-15 02:19
@rafaelks , The members list is ok.
I want to add someone into this room, then click add button on the right-top, but i can not searched any user.

**Comment by oceanho** [comment] 2019-02-15 06:04
@rafaelks. We upgraded the Rocket server to `0.71.1`, then it's work fine.

**Comment by rafaelks** [comment] 2019-02-15 12:15
Great, closing the issue.

**Closed by rafaelks** 2019-02-15 12:15 UTC

**Comment by pwl0lwp** [comment] 2019-05-22 14:13
hello - i’m seeing this bug as a user, with app version 3.5.0 and server version 0.74.3 - was was a regression introduced ?

**Comment by saroar** [comment] 2019-11-18 09:28
here I update code which works for me 

```
extension Subscription {
    func canInviteUsers(user: User? = AuthManager.currentUser()) -> Bool {
        guard let user = user else {
            return false
        }

        if isJoined() && user.hasPermission(.addUserToJoinedRoom, subscription: self) {
            return true
        }

        if type == .channel && user.hasPermission(.addUserToAnyChannelRoom, subscription: self) {
            return true
        }

        if type == .group && user.hasPermission(.addUserToAnyPrivateRoom, subscription: self) {
            return true
        }

        // Creator Group and Channel now can add users
        if type == .group ||  type == .channel && self.roomOwnerId == AuthManager.currentUser()?.identifier {
            return true
        }
        
        return false
    }
}

```
@rafaelks please let me know if its look good for you
