### ISSUE TITLE
[BUG] Layout is not respecting safe areas on iPhone X when viewing a video

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#1604] opened 2018-04-26 11:08 UTC
![img_4900](https://user-images.githubusercontent.com/551004/39302453-09752f50-4929-11e8-8bee-817d5e558dee.PNG)

**Comment by cardoso** [comment] 2018-07-24 18:55
Cannot reproduce.
Probably closed by https://github.com/RocketChat/Rocket.Chat.iOS/pull/1790

**Closed by cardoso** 2018-07-24 18:55 UTC
Labels: 🐛 bug
