### ISSUE TITLE
[BUG] Chat room > Delete > Message was not deleted immediately

### ISSUE THREAD

**Issue by YanniStaMaria** [RocketChat/Rocket.Chat.iOS#2169] opened 2018-09-04 01:40 UTC
Environment:
Rocket Chat App version 3.1.0 (209)
Device (or simulator) you're running with: iPad Pro IOS 11.4.1 and iPhone 6+ IOS 11.3.1

Pre-Condition:
User is logged in. 
User is in a chat room with messages.

Steps:
1. Long press own message
- Verify Message options modal
2. Click Delete Message option
- Verify confirmation message
3. Click "Yes, delete" button on the confirmation message
- Verify chat room

Expected Result
Message should be deleted

Actual Result:
Message was not delete immediately

Please see attached video:
https://www.dropbox.com/s/9k75msp4xoq89br/Video%20Sep%2004%2C%209%2025%2021%20AM.mp4?dl=0

**Comment by cardoso** [comment] 2018-09-04 14:07
This should've been fixed by https://github.com/RocketChat/Rocket.Chat.iOS/pull/2127

And I can't reproduce it anymore.

**Closed by cardoso** 2018-09-04 14:07 UTC
