### ISSUE TITLE
Typing a message with an external keyboard doesn't show it on the chat list

### ISSUE THREAD

**Issue by CharlesVu** [RocketChat/Rocket.Chat.iOS#516] opened 2017-06-22 16:50 UTC
- Your Rocket.Chat app version: 1.1.2
- Your Rocket.Chat server version: 0.56
- Device you're running with: iPhone 6, iOS 10.3.2

Repro steps:
- Connect an external keyboard to your iOS device (using the Anne Pro in my case)
- Enter a room and start typing a message with your external keyboard
- Press enter on your external keyboard
- See the textfield cleared and the message sent

Expected: 
- See your message in the chat above
![img_0337](https://user-images.githubusercontent.com/753278/27445881-6b35dac6-5773-11e7-8a77-354dc8a3cc1f.PNG)

Actual:
- The message is not displayed

Note: the mac client display the message properly.
<img width="439" alt="mac client" src="https://user-images.githubusercontent.com/753278/27445902-7a9579ae-5773-11e7-9658-4e19dc8f1203.png">

**Comment by rafaelks** [comment] 2017-06-23 11:27
@CharlesVu Oh, this is very weird! I'll need to investigate it, because I always use the app on my iPad with an external keyboard, and it works just fine.

**Comment by rafaelks** [comment] 2017-07-13 13:28
Can't reproduce this issue, are you sure it's related to the external keyboard? I'm gonna close it for now.

**Closed by rafaelks** 2017-07-13 13:28 UTC
Labels: investigate
