### ISSUE TITLE
Presence and Message update 

### ISSUE THREAD

**Issue by ChrisKendallVA** [RocketChat/Rocket.Chat.iOS#1689] opened 2018-05-21 22:12 UTC
- Your Rocket.Chat app version: 2.4.0
- Your Rocket.Chat server version: 0.64.0
- Device (or Simulator) you're running with: iPhone 6s

Issue: 
 - Presence displays as offline for all users when loading up the application and doesn’t appear to rectify itself as in delayed loading.
 - Message push banners display and send correctly but messages are not updated correctly with the recent messages.

**Comment by esolix** [comment] 2018-05-22 22:48
Same issue on my setup (three different instances)

RocketChat App IOS v 2.40
RocketChat Server V 0.64.2
Iphone 8 Plus- iOS v 11.3.1

**Comment by kaiiiiiiiii** [comment] 2018-05-22 22:56
Duplicate of #1681, closed by #1685 and #1707, currently in beta testing.

Cheers

**Comment by cardoso** [comment] 2018-05-22 23:57
Thanks @kaiiiiiiiii

**Closed by cardoso** 2018-05-22 23:57 UTC

**Comment by rafaelks** [comment] 2018-05-23 11:50
Currently status: we're waiting for Apple to approve the beta builds for external testers and to approve it to the App Store. :-)
