### ISSUE TITLE
[BUG] Sidebar stays blank

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1215] opened 2018-01-29 07:12 UTC
Got it the first time with the current 2.0 build after switching to RC and opening the sidebar. Currently can't reproduce.
Sidebar is recovered when sliding back to chat and opening sidebar again.
![285545e6-8413-4c46-9d07-2d5747023314](https://user-images.githubusercontent.com/193273/35497831-25e7949e-04cc-11e8-9f53-e88454036b3d.jpeg)

**Comment by rafaelks** [comment] 2018-02-05 14:32
I also reproduced this one. Since we're changing the layout, let's just close it because this bug won't happen again.

**Closed by rafaelks** 2018-02-05 14:32 UTC
