### ISSUE TITLE
[BUG] Join the Community > Continue with Facebook > Landing page keeps on loading

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.iOS#1894] opened 2018-07-06 05:03 UTC
Environment:
Rocket Chat App version 3.0.0 (188)
Device (or simulator) you're running with: iPad 5th gen ios 11.1.2

Pre-Condition:
Rocket.Chat fresh installed

Steps:
1. Launch Rocket Chat app
2. Tap Join The Community
3. Tap Continue with Facebook

Expected Result
Facebook sign in page should open without any issue

Actual Result
Landing page keeps on loading

Please see attached photos
![b1osvd3gq](https://user-images.githubusercontent.com/38445437/42360662-b8eb62b2-811c-11e8-98ef-0bac7abef6cf.png)
![rk2addngq](https://user-images.githubusercontent.com/38445437/42360676-d566fef6-811c-11e8-97d6-cec2e27c7dee.png)

**Comment by rafaelks** [comment] 2018-07-06 14:55
It is working fine for me...

![simulator screen shot - iphone se - 2018-07-06 at 11 53 28](https://user-images.githubusercontent.com/551004/42385531-685c1f84-8113-11e8-8bd5-67395df69b45.png)

![simulator screen shot - ipad pro 10 5-inch - 2018-07-06 at 11 55 01](https://user-images.githubusercontent.com/551004/42385536-6cb113be-8113-11e8-9518-7620618eb8c9.png)

**Comment by filipealva** [comment] 2018-07-06 18:09
I could not reproduce this one as well.

**Comment by filipealva** [comment] 2018-07-09 14:30
I'm closing this one since we are not able to reproduce the issue

**Closed by filipealva** 2018-07-09 14:30 UTC
Labels: 🐛 bug
