### ISSUE TITLE
Administration from iOS app - menu not working

### ISSUE THREAD

**Issue by JEREYMNO** [RocketChat/Rocket.Chat.iOS#2014] opened 2018-07-18 10:36 UTC
Hi,

open administration from app after some updates stoped working. Menu button dont alow me to open menu panel for admin. From sfari directly on same device working without problem. Try to delete and download app again but problem presist. 

- Your Rocket.Chat app version: 3.0.0 (197)
- Your Rocket.Chat server version: 0.66.2
- Device (or Simulator) you're running with: iPhone X

![img_3e87339e65e7-1](https://user-images.githubusercontent.com/31340507/42876472-11860814-8a87-11e8-89b7-1dc23f6e4205.jpeg)

**Comment by rafaelks** [comment] 2018-07-18 14:55
@JEREYMNO Thanks for pointing that to us, just created the issue on the back-end repository: https://github.com/RocketChat/Rocket.Chat/issues/11494.

Will close this one for now, since the issue is on the web client.

**Closed by rafaelks** 2018-07-18 14:55 UTC
