### ISSUE TITLE
[BUG-SERVER] Avatars are strange after v3 update

### ISSUE THREAD

**Issue by boblmartens** [RocketChat/Rocket.Chat.iOS#2038] opened 2018-07-19 13:13 UTC
- Your Rocket.Chat app version: 3.0.1
- Your Rocket.Chat server version: 0.66.2
- Device (or Simulator) you're running with: iPhone 7 w/iOS 11.4.1

With the update to v3, avatars for rooms and persons (who have not set an avatar) are strange/wonky. I have included an image to show what I mean.

![img_5339](https://user-images.githubusercontent.com/12119/42944513-6f11cc30-8b2b-11e8-958c-9476f93db81e.jpg)

I am wondering if I have set something wrong or if there is a bug that I am hitting. Thanks!

**Comment by boblmartens** [comment] 2018-07-19 13:13
Obviously Aaron set his own avatar, which is why it shows up correctly.

**Comment by rafaelks** [comment] 2018-07-19 13:17
@boblmartens HAHAHAHAHAH! Great idea from Aaron! :-)

The problem is related to the installation of your server... you're missing some font used to generate the avatars. Are you guys using snap installation?

**Comment by boblmartens** [comment] 2018-07-19 13:17
I am using the snap.

**Comment by rafaelks** [comment] 2018-07-19 13:18
@geekgonecrazy Looks like the font problem is back again... do you have any idea what's causing this?

**Comment by geekgonecrazy** [comment] 2018-07-19 23:28
@boblmartens can you open a browser and try to load something like: http://{your server}/avatar/{username}?format=jpg

Just tried in local install and didn't have an issue, so hope we can get to bottom of it.

**Comment by boblmartens** [comment] 2018-07-20 01:42
https://chat.mlc-wels.edu/avatar/kramerlm?format=jpg

Looks like that might be where the issue is. What should I be looking for on the server?

**Comment by geekgonecrazy** [comment] 2018-07-20 06:19
@boblmartens try a `sudo snap refresh rocketchat-server` and see if that fixes it for you.  I released a fix thanks :)

**Comment by boblmartens** [comment] 2018-07-20 12:43
Thanks!

**Comment by boblmartens** [comment] 2018-07-20 13:01
Refreshed the snap and some of the avatars are working, and others are not. Could the image be cached in the iOS app somehow?

**Comment by rafaelks** [comment] 2018-07-20 14:24
@boblmartens The iOS app has some caching on the images, yes. If you want them to be gone forever, you'll need to reinstall the app now. This is going to be fixed in couple of releases with a change in the back-end.

**Closed by rafaelks** 2018-07-20 14:24 UTC
