### ISSUE TITLE
Please add an Edit option in the app

### ISSUE THREAD

**Issue by SamSaffron** [RocketChat/Rocket.Chat.iOS#1140] opened 2018-01-09 23:35 UTC
At the moment there is no way to edit messages from the app. Can this be added?

**Comment by soundstorm** [comment] 2018-01-10 10:03
Duplicate of #1097

**Comment by rafaelks** [comment] 2018-01-10 15:25
Closing because it's duplicated. @SamSaffron There's an open PR with this feature, we'll work to merge this for the next release. 👍

**Closed by rafaelks** 2018-01-10 15:25 UTC
