### ISSUE TITLE
[BUG] Not able to upload image / video / doc / pdf file to official Cloud Rocket.chat solution

### ISSUE THREAD

**Issue by VassiliM** [RocketChat/Rocket.Chat.iOS#1092] opened 2017-12-28 23:54 UTC
When I try to upload a file (take a picture, shoot video, or  import file from explorer), there is a nice message "on-going upload" but at the end, nothing happen and there is no information in the server logs.

- Rocket.Chat+ app version: 1.7.4 (126)
- Rocket.Chat server version: 0.59.4 on official Rocket.chat cloud solution
- Device (or Simulator) : IPhone 6s (IOS 11.1.1)

Note : With the Cordova one (called Rocket.Chat in the App Store) or the App on Windows, there is no issue.

**Comment by rafaelks** [comment] 2017-12-29 14:59
@VassiliM Is it always reproducible? If you kill the app and start again will it work?

**Comment by VassiliM** [comment] 2017-12-30 23:01
On my iphone:
- Rocket.chat+ killed and restarted several times. 
- Rocket.chat+ uninstalled and reinstalled.

Another test with Rocket.chat+ App :
- I can publish a picture on open.rocket.chat and see the result.
- However I can't publish on my new xxx.rocket.chat cloud solution managed by rocket.chat. And I can't see pictures published by other people. 

Same test with Rocket.chat App : no issue.

**Comment by rafaelks** [comment] 2018-01-02 10:54
@VassiliM Could you please check if your server is using 0.60? Because we do have a **critical bug** that implies this bug in our mobile client. If that's the case, we need to update your server to 0.60.2.

**Comment by VassiliM** [comment] 2018-01-02 12:34
The default version provided by Rocket.Chat Cloud is currently v 0.59.4, released end november. I just wrote to rocket.chat team in order to have the last release on their cloud solution.

**Comment by VassiliM** [comment] 2018-01-03 18:43
Rocket.chat Cloud solution updated by Rocket.chat team, with the release v0.60.2. 
Issue not solved. Could it be related to the storage used and defined by Rocket.chat team (aka GoogleCloudStorage ) ? 

Logs:
LocalStore: store created at  
LocalStore: store created at  
LocalStore: store created at  
LocalStore: store created at  
Setting default file store to GoogleCloudStorage 
Using GridFS for custom sounds storage 
Using GridFS for custom emoji storage 
ufs: temp directory created at "/tmp/ufs" 
Setting default file store to GoogleCloudStorage

**Comment by rafaelks** [comment] 2018-01-05 10:02
@VassiliM Can you give me a screenshot of your "File Upload" page in Administration page? Also, if you can, create an account in `open.rocket.chat` and try to upload the file over there... because it's the same hosting & same settings (probably, that's what I want to check). Thank you!

**Comment by rafaelks** [comment] 2018-02-22 00:39
@VassiliM Is this issue resolved? I'm closing here for now.

**Closed by rafaelks** 2018-02-22 00:39 UTC
Labels: bug, needs more info
