### ISSUE TITLE
Can not pass the unsupported version warning window

### ISSUE THREAD

**Issue by lamersons** [RocketChat/Rocket.Chat.iOS#401] opened 2017-04-03 13:53 UTC
Can not pass the unsupported version warning window

The server you are trying to connect is using a version that's not supported by the app anymore: 0.48.2 We require version 0.54.0

- Your Rocket.Chat app version: 1.0.6
- Your Rocket.Chat server version: 0.48.2
- Device (or Simulator) you're running with:  iPhone 6, iOS 10.3, ipad2 10.3

**Comment by rafaelks** [comment] 2017-04-04 12:19
@lamersons Thanks for opening the issue. I'll investigate it more deeper, because I couldn't reproduce it at the first time. Can you confirm to me what's your server URL?

**Comment by rafaelks** [comment] 2017-04-13 12:58
Closing, because I need more info.

**Closed by rafaelks** 2017-04-13 12:58 UTC
Labels: bug, investigate, needs more info

**Comment by FAD0** [comment] 2017-04-26 11:40
I am getting the same error.  I downloaded RocketChat+ from the Apple App store.  The original Rocketchat app works but doesn't let me scroll so is not usable.  For RocketChat+, I put in my ngrok address and it comes up with the same "warning":

"The server you're trying to connect is using a version that's not supported by the app anymore: 0.39.0.

We require version 0.54.0."

I am using iPhone 6, iOS version 10.3.1.

It is able to connect to the ngrok address, which tunnels to my raspberrypi on my home network.  But when I try to log on it never completes, it just keeps giving me the ..., ..., ... over and over.

I know the ngrok tunnel is working because I can connect and chat with the original Rocketchat app, but since I can't scroll, I can really do much with that app.  I think Rocketchat+ will work if I can just get past this one issue.  Thanks.

**Comment by FAD0** [comment] 2017-04-26 11:41
Can you please reopen this issue?  Or should I file a new one?

**Comment by rafaelks** [comment] 2017-04-26 11:49
@FAD0 It seems that the issue isn't exactly the same, because you're able to connect to the server. What server version are you using? Can you see the logs and see what's the latest request the app makes to the server?

**Comment by FAD0** [comment] 2017-04-26 12:05
In the warning it says I am connecting to server 0.39.0.  Okay, I checked the log file on my raspberrypi 2, which is the "server" I guess, and I have confirmed it is version 0.39.0.  But I just re-downloaded and reinstalled Rocketchat today, so it should be the latest version.  Maybe RocketChat+ doesn't support the current raspberrypi version on Rocketchat as a server?

**Comment by FAD0** [comment] 2017-04-26 12:09
Let me try some things and get back to you.  I have been following this tutorial: https://www.youtube.com/watch?v=BevcvRLsa9Y.  Let me see if I can figure out how to update my Rocketchat server to 0.54 or higher...

**Comment by rafaelks** [comment] 2017-04-26 12:34
@FAD0 Yeah, that's probably because your server is *very* old. Try updating it please.

**Comment by FAD0** [comment] 2017-04-26 12:55
It seems 0.39.0 is the latest rocket chat for raspberry pi: https://github.com/RocketChat/Rocket.Chat.RaspberryPi

I have tried downloading 0.54.2 from rocket.chat/download for debian and it gives me errors: 
module.js:340
   throw err:

Error: cannot find module 'fibers'
...

So it looks like I can't use RocketChat+ with raspberrypi as a server.
