### ISSUE TITLE
[BUG] Messages sent with bad network connection are causing the room to stuck in the app

### ISSUE THREAD

**Issue by codingheld** [RocketChat/Rocket.Chat.iOS#2437] opened 2018-12-19 14:51 UTC
- Rocket.Chat app version: 3.2.0
- Rocket.Chat server version: 0.72.3
- Device : iPhone X, iOS 12.1

When the user has a bad network connection and is trying to write his first ever message to another user he gets infinite loading animation in this room and the message is not send without any error message. 
Later, if there is a good connection the user is not able so send any other message to this user (=room) anymore. The room is not visible in server.

Writing another Message with the web/desktop client opens a new room on the phone an he is able to communicate with the desired user. 
Meanwhile the "broken" room is visible in search on the app (+ the "not broken" room)

**Comment by codingheld** [comment] 2018-12-20 08:12
I did some further investigations. Steps to reproduce:
- Open App (master) in iOS Simulator
- Lower quality of network with "Network Link Conditioner": 
![image](https://user-images.githubusercontent.com/6906923/50271904-6faf1100-0436-11e9-8ad6-77795b6fbb11.png)
(trying to simulate bad wifi, broken wifi station, open wifi with captive portal)

- Search for user with no previous messages and send a message. Error:
`[REST][RESULT][ERROR][https://chat.XXX.de/api/v1/chat.sendMessage]: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7b0c0016b510 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://chat.XXX.de/api/v1/chat.sendMessage, NSErrorFailingURLKey=https://chat.XXX.de/api/v1/chat.sendMessage, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=60, NSLocalizedDescription=The request timed out.}`

- Sending message later with good network causes this error:
`[ERROR][SocketManager]: Invalid message id [error-invalid-message_id]
[REST][REQUEST]: https://chat.XXX.de/api/v1/chat.sendMessage: {
  "message" : {
    "rid" : "",
    "_id" : "tg7SgyuDiYgcSNoNDB",
    "msg" : "Sdsd"
  }
}`

- Write some message in a room which was already created show the read exclamation mark and adds the ability to resend the message

**Comment by rafaelks** [comment] 2018-12-21 11:58
@codingheld Thanks for the investigation! I'm going to add this bug to our next release. 👍

**Comment by matthewbassett** [comment] 2019-02-07 02:24
I'd like to bump this one a bit. I originally closed my bug report #2504 thinking it was a duplicate of this one, and I saw it in the dev cycle for 01/05-02/05. However I wanted to bring this back up, because this bug is a show stopper for our organization. According to this bug it says that a poor network connection causes this, however in my instance any time I try to message a user that has not been messaged from my account before you get the three loading dots like its trying to pull up history, and then it just hangs there, you try to write messages and send them but they never go through. If I pull it up in safari on the same device then it works flawlessly and send the message immediately. Eventually after 3-4 hours I will be able to send messages to that person.
I can also send messages to people who initiate a conversation with me first.

Thoughts on whether or not this is the same bug or a different issue?

Thanks!

**Comment by rafaelks** [comment] 2019-02-08 12:49
@matthewbassett Thanks for the feedback. I believe your bug is related to only new conversations instead of any conversation... can you confirm if that's the case? Have you tried version 3.3 already? We made some changes on this flow in latest release to prevent this from happening with new conversations. Thank you!

**Comment by matthewbassett** [comment] 2019-02-09 02:31
@rafaelks It doesn't really fix the issue, but it does appear to have changed the issue a bit. If you'd like me to open up a new bug report for this I can just let me know.
Now when I search for someone I have not messaged before and select that person it displays the card that says "This is the start of your conversation with" however it is not the person I selected to chat with (It is alphabetically the first person in the directory) at the top of the window it still says the name of the person I selected, however when I select different new contacts to chat with I still see the same alphabetically first name card and the message that I sent to the first new contact. I am also noticing that the search gets knocked off by one as well, you can see that when I have someone selected on the left it doesn't necessarily show the same person at the top right as selected. Hopefully I'm explaining this correctly... I also attached a few images to show it. Again, if I should open seperate bug reports for these so they can be addressed one at a time I'm happy to do that 👍 
![img_2092](https://user-images.githubusercontent.com/7525172/52515374-a4c92a00-2c55-11e9-8cf0-dec05ceca033.PNG)
![img_2093](https://user-images.githubusercontent.com/7525172/52515375-a4c92a00-2c55-11e9-9e01-20dfba5bb8a5.PNG)
![img_2094](https://user-images.githubusercontent.com/7525172/52515376-a561c080-2c55-11e9-80dc-a5bdca746ffa.PNG)
![img_2095](https://user-images.githubusercontent.com/7525172/52515378-a5fa5700-2c55-11e9-87e1-931db4e216df.PNG)

**Comment by matthewbassett** [comment] 2019-02-09 02:41
I believe what is happening with it selecting a different user in the list then is actually selected is that the person original "test" message was intended to go to disappears from the search list view, but didn't actually disappear from the list so it is still selectable. Hopefully this is helpful information.

**Comment by juli3n31** [comment] 2019-02-11 11:04
same problem for me:
      Server version 0.74.2
      IOS App: 3.3.0 (236)
Available if needed other information or test.

**Comment by rafaelks** [comment] 2019-02-11 12:44
@matthewbassett That's very strange, but we're going to investigate the issue you reported. 👍

**Comment by matthewbassett** [comment] 2019-02-12 05:15
@rafaelks Thanks! we really appreciate it! We are rolling RC out across our org, and not being able to message someone new from the iOS app is a show stopper for sure. Thanks again for all your great work!

**Comment by rafaelks** [comment] 2019-02-12 11:39
@matthewbassett I'm working on this fix right now and will be sending a hot fix with the problem resolved very soon. 👍

**Comment by matthewbassett** [comment] 2019-02-12 12:37
@rafaelks Awesome (: quick work!

**Closed** 2019-02-12 12:38 UTC
Labels: 🐛 bug

**Comment by rafaelks** [comment] 2019-02-12 12:39
I'll be sending a fix to TestFlight soon, please join here to see if that works for you guys: https://testflight.apple.com/join/3gcYeoMr.

**Comment by juli3n31** [comment] 2019-02-12 14:01
Hello rafaelks,
i run the test and I don't see any change on my side.

**Comment by codingheld** [comment] 2019-02-12 14:01
Doesn't work for me. Especially the issue @matthewbassett reported occurs:
- I am writing to user M*****s but selected ist "A******" (the first in our organization, sorted by name)
- Message is not send/room is not created

![img_41ce1597e892-1](https://user-images.githubusercontent.com/6906923/52640566-1237bd80-2ed7-11e9-8a15-ea84db6744b2.png)

**Comment by rafaelks** [comment] 2019-02-12 14:29
@codingheld Version 3.3.1 is not available yet, you will receive a notification when it gets available. Thanks!

**Comment by codingheld** [comment] 2019-02-13 11:00
@rafaelks The testflight build fixes our problem. Thanks! When do you plan to ship this fix?

**Comment by rafaelks** [comment] 2019-02-13 11:02
@codingheld Amazing, as soon as Apple approves it!

**Comment by juli3n31** [comment] 2019-02-13 11:20
problem solved also
good job !
